# Generated by Django 3.0.6 on 2020-06-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafields',
            old_name='modeltype',
            new_name='modelType',
        ),
    ]
